#!/bin/sh
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Initialises a Terraform stack against the shared GCS state bucket.
#
# The stack itself declares no backend, so a plain `terraform init` keeps using
# local state. This script adds the GCS backend through an override file
# (gcs_backend_override.tf, ignored by git) and then initialises it, which is
# how the pipeline and anyone running Terraform by hand share one state.
#
# Environment:
#   TF_STATE_BUCKET  (required) the state bucket created by terraform/bootstrap
#   TF_STATE_PREFIX  object prefix inside the bucket (default: terraform/gcp)
#   TF_DIR           the stack directory (default: terraform/gcp)

set -eu

: "${TF_STATE_BUCKET:?TF_STATE_BUCKET must name the Terraform state bucket}"
TF_STATE_PREFIX="${TF_STATE_PREFIX:-terraform/gcp}"
TF_DIR="${TF_DIR:-terraform/gcp}"

if [ ! -d "$TF_DIR" ]; then
  echo "TF_DIR=$TF_DIR is not a directory." >&2
  exit 1
fi

export TF_IN_AUTOMATION="${TF_IN_AUTOMATION:-1}"
export TF_INPUT=0

cat > "$TF_DIR/gcs_backend_override.tf" <<'EOF'
# Generated by scripts/ci/tf_init.sh. Not committed (matches *_override.tf).
terraform {
  backend "gcs" {}
}
EOF

echo "Terraform state: gs://$TF_STATE_BUCKET/$TF_STATE_PREFIX"
terraform -chdir="$TF_DIR" init -input=false -reconfigure \
  -backend-config="bucket=$TF_STATE_BUCKET" \
  -backend-config="prefix=$TF_STATE_PREFIX"
